---

- name: jenkins_master | install jenkins specific system packages
  apt:
    pkg={{",".join(jenkins_debian_pkgs)}}
    state=present update_cache=yes
  tags:
  - jenkins

- name: jenkins_master | Create jenkins group
  group: name={{ jenkins_group }} state=present

- name: jenkins_master | Add the jenkins user to the group
  user: name={{ jenkins_user }} append=yes group={{ jenkins_group }} state=present

- name: jenkins_master | Install Jenkins apt key
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present

- name: jenkins_master | Add apt repository
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present

- name: jenkins_master | Install jenkins package
  apt: pkg=jenkins state=present update_cache=yes

- name: jenkins_master | Stop Jenkins
  service: name=jenkins state=stopped

- name: jenkins_master | Set owner for Jenkins home
  file: path={{ jenkins_home }} recurse=yes state=directory
        owner={{ jenkins_user }} group={{ jenkins_group }}

- name: jenkins_master | Make plugins directory
  sudo_user: jenkins
  shell: mkdir -p {{ jenkins_home }}/plugins

- name: jenkins_master | Install Jenkins plugins
  sudo_user: jenkins
  get_url: url=http://updates.jenkins-ci.org/download/plugins/${item.name}/${item.version}/${item.name}.hpi
           dest={{ jenkins_home }}/plugins/${item.name}.hpi
  with_items: "{{ jenkins_plugins }}"
  notify:
    - jenkins_master | restart Jenkins

- name: jenkins_master | Setup nginx vhost
  template:
    src=etc/nginx/sites-available/jenkins.j2
    dest=/etc/nginx/sites-available/jenkins
  notify: jenkins_master | reload nginx

- name: jenkins_master | enable jenkins vhost
  file:
    src=/etc/nginx/sites-available/jenkins
    dest=/etc/nginx/sites-enabled/jenkins
    state=link
  notify: jenkins_master | reload nginx

- name: jenkins_master | remove nginx default site
  file:
    path=/etc/nginx/sites-enabled/default
    state=absent
  notify: jenkins_master | reload nginx
